### ISSUE TITLE
po2dtd doesn't cope with removed spaces

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#183]
_Version: 0.8rc6_

Bug #79 solved the compaction of pretty printed spaces.  However merging back
seems to be a problem now:

Here is a traceback:

[dwayne@laptop-wifi convert]$ python po2dtd.py -t incompatible.dtd
incompatible.dtd.po incompatible.dtd.tn --errorlevel=traceback
processing 1 files...

po2dtd.py: warning: Error processing: input incompatible.dtd.po, output
incompatible.dtd.tn, template incompatible.dtd: Traceback (most recent call last):

  File "/usr/lib/python2.4/site-packages/translate/misc/optrecurse.py", line
418, in recursiveprocess
    success = self.processfile(fileprocessor, options, fullinputpath,
fulloutputpath, fulltemplatepath)

  File "/usr/lib/python2.4/site-packages/translate/misc/optrecurse.py", line
471, in processfile
    if fileprocessor(inputfile, outputfile, templatefile, **passthroughoptions):

  File "po2dtd.py", line 262, in convertdtd
    outputdtdsrc = str(outputdtd)

  File "/usr/lib/python2.4/site-packages/translate/storage/dtd.py", line 276, in
**str**
    source = self.getsource()

  File "/usr/lib/python2.4/site-packages/translate/storage/dtd.py", line 283, in
getsource
    sources = [str(dtd) for dtd in self.dtdelements]

  File "/usr/lib/python2.4/site-packages/translate/storage/dtd.py", line 209, in
**str**
    source = self.getsource()

  File "/usr/lib/python2.4/site-packages/translate/storage/dtd.py", line 220, in
getsource
    raise StopIteration()

StopIteration

**Comment by linuxjackto1** [comment]
thanks www.movied.org
