### ISSUE TITLE
translate.storage.mo confuses major and minor revision in little-endian MO files

### ISSUE THREAD

**Issue by llimeht** [translate/translate#3072]
_Version: 1.10.0_

_Created [attachment 944](http://bugs.locamotion.org/attachment.cgi?id=944)_

Sample MO file

As reported in Debian bug #714214 [1], Jakub Wilk discovered that translate toolkit misunderstands little-endian MO files. He writes:

I crafted a little-endian MO file with revision 0.42. translate-toolkit 
refuses to open it, saying the revision is 42.0:

> > > from translate.storage.mo import mofile
> > > mofile(open('messages.mo'))
> > > Traceback (most recent call last):
> > >    File "<stdin>", line 1, in <module>
> > >    File "/usr/lib/python2.7/dist-packages/translate/storage/mo.py", line 147, in **init**
> > >      self.parsestring(inputfile)
> > >    File "/usr/lib/python2.7/dist-packages/translate/storage/base.py", line 729, in parsestring
> > >      newstore.parse(storestring)
> > >    File "/usr/lib/python2.7/dist-packages/translate/storage/mo.py", line 262, in parse
> > >      raise base.ParseError("""Unable to process version %d.%d MO files""" % (version_maj, version_min))
> > > translate.storage.base.ParseError: 'Unable to process version 42.0 MO files'

[1] http://bugs.debian.org/714214

**Comment by llimeht** [comment]
To update the reproducer, this is still present in translate-toolkit version 3.15.6:

```
>>> from translate.storage.mo import mofile
>>> mofile(open('messages.mo', 'rb'))
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    mofile(open('messages.mo', 'rb'))
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/translate/storage/mo.py", line 151, in __init__
    self.parsestring(inputfile)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/translate/storage/base.py", line 817, in parsestring
    newstore.parse(storestring)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/translate/storage/mo.py", line 299, in parse
    raise base.ParseError(
    ...<2 lines>...
    )
translate.storage.base.ParseError: 'Unable to process version 42.0 MO files'
```

(there are other endianness problems - more on that in a bit)
