### ISSUE TITLE
Faulty error message while initializing properties storage

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#3194]
*Version: trunk*

*Originally posted by Kevin KIN-FOO:*

Hi,

Using Pootle, I got the following:

```
$ python manage.py update_against_templates
e
2014-04-15 17:18:12,266 INFO Loading custom settings from '/w/avpootle/av.conf'...
2014-04-15 15:18:12,432 INFO Using Python PO
<type 'NoneType'>
2014-04-15 15:18:12,505 ERROR Failed to run update_against_templates over /de/airvantage/:
Cannot detect encoding for 
Traceback (most recent call last):
  File "/home/kevin/Development/pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 51, in do_translation_project
    process_stores = self.handle_translation_project(tp, **options)
  File "/home/kevin/Development/pootle/pootle/apps/pootle_app/management/commands/update_against_templates.py", line 32, in handle_translation_project
    translation_project.update_against_templates()
  File "/home/kevin/Development/pootle/pootle/apps/pootle_translationproject/models.py", line 425, in update_against_templates
    monolingual)
  File "/home/kevin/Development/pootle/pootle/apps/pootle_app/project_tree.py", line 377, in convert_template
    template_file = template_store.file.store
  File "/home/kevin/Development/pootle/pootle/apps/pootle_store/fields.py", line 170, in store
    self._update_store_cache()
  File "/home/kevin/Development/pootle/pootle/apps/pootle_store/fields.py", line 191, in _update_store_cache
    classes=factory_classes)
  File "/home/kevin/.virtualenvs/pootle/src/translate-toolkit/translate/storage/factory.py", line 188, in getobject
    store = storeclass.parsefile(storefile)
  File "/home/kevin/.virtualenvs/pootle/src/translate-toolkit/translate/storage/base.py", line 829, in parsefile
    newstore = cls.parsestring(storestring)
  File "/home/kevin/.virtualenvs/pootle/src/translate-toolkit/translate/storage/base.py", line 728, in parsestring
    newstore.parse(storestring)
  File "/home/kevin/.virtualenvs/pootle/src/translate-toolkit/translate/storage/properties.py", line 570, in parse
    raise IOError("Cannot detect encoding for %s" %  self.filename)
```

Reading the code I understand that there is an attempt to provide error message, in this case there is no file name to provide as a string is being dealt with. I think a different message should be provided for this use case.

**Comment by claudep** [comment]
Fixed in f83c7fa6
