### ISSUE TITLE
[VirtualEnv] ImportError: No module named __version__

### ISSUE THREAD

**Issue by arky** [translate/translate#3226]
Using Virtualenv (virtualenvwrapper 3.7) with Python 2.7.8 on Ubuntu 14.10. The translate-toolkit throws following error when running 

$ python manage.py syncdb --noinput

```pytb 
2014-10-30 12:58:17,683 INFO Using Python PO
2014-10-30 12:58:17,816 WARNING Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
Traceback (most recent call last):
  File "manage.py", line 32, in <module>
    execute_from_command_line()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/debug_toolbar/models.py", line 9, in <module>
    dt_settings.patch_all()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 238, in patch_all
    patch_root_urlconf()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 226, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 507, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 290, in _populate
    for name in pattern.reverse_dict:
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 315, in reverse_dict
    self._populate()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 290, in _populate
    for name in pattern.reverse_dict:
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 315, in reverse_dict
    self._populate()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/arky/src/pootle/pootle/apps/pootle_app/views/index/about.py", line 21, in <module>
    from translate.__version__ import sver as toolkit_version
ImportError: No module named __version__
```

**Comment by claudep** [comment]
I'd bet this is related to some bad installation or bad Python path, I don't see what could be done on the translate toolkit side.
