### ISSUE TITLE
po2xliff problem

### ISSUE THREAD

**Issue by feirouu** [translate/translate#3382]
I run this command:

```
po2xliff -t test.xliff test.po result.xliff --errorlevel=traceback
```

The error:

```
processing 1 files...
WARNING:po2xliff:Error processing: input test.po, output result.xliff, template test.xliff: Traceback (most recent call last):

File "/Library/Python/2.7/site-packages/translate/misc/optrecurse.py", line 514, in recursiveprocess fulltemplatepath)

File "/Library/Python/2.7/site-packages/translate/convert/convert.py", line 179, in processfile fulltemplatepath)

File "/Library/Python/2.7/site-packages/translate/misc/optrecurse.py", line 572, in processfile **passthroughoptions):

File "/Library/Python/2.7/site-packages/translate/convert/po2xliff.py", line 99, in convertpo outputstring = convertor.convertstore(inputstore, templatefile)

File "/Library/Python/2.7/site-packages/translate/convert/po2xliff.py", line 89, in convertstore transunitnode = self.convertunit(outputstore, inputunit, filename)

File "/Library/Python/2.7/site-packages/translate/convert/po2xliff.py", line 37, in convertunit unit = outputstore.addheaderunit(target, filename)

File "/Library/Python/2.7/site-packages/translate/storage/poxliff.py", line 309, in addheaderunit unit.target = target

File "/Library/Python/2.7/site-packages/translate/storage/poxliff.py", line 129, in settarget super(PoXliffUnit, self).settarget(text, lang, append)

File "/Library/Python/2.7/site-packages/translate/storage/xliff.py", line 391, in settarget super(xliffunit, self).settarget(text, lang, append)

File "/Library/Python/2.7/site-packages/translate/storage/lisa.py", line 155, in settarget self.set_target_dom(languageNode, append)

File "/Library/Python/2.7/site-packages/translate/storage/lisa.py", line 123, in set_target_dom assert len(languageNodes) > 0

AssertionError

[###########################################] 100%
```

**Comment by dwaynebailey** [comment]
@JunyuMu could it be that test.xliff has multiple language in it? I'm not sure we support multiple languages in xliff files.

**Comment by JunyuMu** [comment]
@dwaynebailey 

## test.xliff
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.0">
     <file source-language="en" datatype="plaintext" original="messages" date="2011-10-18T18:20:51Z" product-name="my-ext">
             <header/>
             <body>
                     <trans-unit id="headerComment" xml:space="preserve">
                             <source>The default Header Comment.</source>
                     </trans-unit>
                     <trans-unit id="generator" xml:space="preserve">
                             <source>The "Generator" Meta Tag.</source>
                     </trans-unit>
             </body>
     </file>
</xliff>
```

**Comment by JunyuMu** [comment]
I  want use po2xliff command for convert po to xliff with template.
i copy this code in test_xliff.py file.
> source.xliff

```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff:xliff version="1.2" xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
    <xliff:file original="doc.txt" source-language="en-US">
        <xliff:body>
            <xliff:trans-unit id="1">
                <xliff:source>File 1</xliff:source>
            </xliff:trans-unit>
        </xliff:body>
    </xliff:file>
</xliff:xliff>
```

First, I use this command to convert po file and translated it
```bash
xliff2po source.xliff source.po
```
> source.po

```po
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-02-26 12:30+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 1.13.0\n"

#: 1
msgid "File 1"
msgstr "Test 111"

```

then, I run
```bash
po2xliff -t source.xliff source.po result.xliff --errorlevel=traceback
```
and get errors:

```bash
processing 1 files...
WARNING:po2xliff:Error processing: input source.po, output result.xliff, template source.xliff: Traceback (most recent call last):

  File "/Library/Python/2.7/site-packages/translate/misc/optrecurse.py", line 514, in recursiveprocess
    fulltemplatepath)

  File "/Library/Python/2.7/site-packages/translate/convert/convert.py", line 179, in processfile
    fulltemplatepath)

  File "/Library/Python/2.7/site-packages/translate/misc/optrecurse.py", line 572, in processfile
    **passthroughoptions):

  File "/Library/Python/2.7/site-packages/translate/convert/po2xliff.py", line 99, in convertpo
    outputstring = convertor.convertstore(inputstore, templatefile)

  File "/Library/Python/2.7/site-packages/translate/convert/po2xliff.py", line 89, in convertstore
    transunitnode = self.convertunit(outputstore, inputunit, filename)

  File "/Library/Python/2.7/site-packages/translate/convert/po2xliff.py", line 37, in convertunit
    unit = outputstore.addheaderunit(target, filename)

  File "/Library/Python/2.7/site-packages/translate/storage/poxliff.py", line 309, in addheaderunit
    unit.target = target

  File "/Library/Python/2.7/site-packages/translate/storage/poxliff.py", line 129, in settarget
    super(PoXliffUnit, self).settarget(text, lang, append)

  File "/Library/Python/2.7/site-packages/translate/storage/xliff.py", line 391, in settarget
    super(xliffunit, self).settarget(text, lang, append)

  File "/Library/Python/2.7/site-packages/translate/storage/lisa.py", line 155, in settarget
    self.set_target_dom(languageNode, append)

  File "/Library/Python/2.7/site-packages/translate/storage/lisa.py", line 123, in set_target_dom
    assert len(languageNodes) > 0

AssertionError

[###########################################] 100%
```

Please help me to fix this issue. Thanks!

**Comment by nijel** [comment]
This works well on the current release,
