### ISSUE TITLE
Traceback when running some commands

### ISSUE THREAD

**Issue by unho** [translate/translate#3383]
@claudep I get this traceback when running `poconflicts`, `pocompile`, `podebug`, `porestructure`, `poswap`, `poterminology`, `pot2po`, `pretranslate`, `tmserver`, `ts2po`, `po2ts`:

```pytb
Traceback (most recent call last):
  File "/usr/bin/podebug", line 22, in <module>
    from translate.tools import podebug
  File "/home/leo/Escritorio/repos/translate/translate/tools/podebug.py", line 32, in <module>
    from translate.convert import dtd2po
  File "/home/leo/Escritorio/repos/translate/translate/convert/dtd2po.py", line 29, in <module>
    from translate.convert.accesskey import UnitMixer
  File "/home/leo/Escritorio/repos/translate/translate/convert/accesskey.py", line 24, in <module>
    from translate.storage.placeables.general import XMLEntityPlaceable
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/__init__.py", line 47, in <module>
    from . import base
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/base.py", line 25, in <module>
    from translate.storage.placeables.interfaces import *
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/interfaces.py", line 25, in <module>
    from translate.storage.placeables.strelem import StringElem
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/strelem.py", line 35, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by unho** [comment]
I have `six==1.9.0` installed.

**Comment by unho** [comment]
And I ensured that when starting a python console with `python` and then executing `import six` works ok.

**Comment by unho** [comment]
@dwaynebailey Pointed out that it is running the command in the OS rather the one in the virtualenv. This is most likely the cause.

**Comment by dwaynebailey** [comment]
@unho I'd close these, They're almost all to do with a bust venv.  Open them if you can replicate them.

**Comment by unho** [comment]
Reopening since the issue persists:

```pytb
Traceback (most recent call last):
  File "/home/leo/Escritorio/repos/translate/translate/tools/podebug.py", line 32, in <module>
    from translate.convert import dtd2po
  File "/home/leo/Escritorio/repos/translate/translate/convert/dtd2po.py", line 29, in <module>
    from translate.convert.accesskey import UnitMixer
  File "/home/leo/Escritorio/repos/translate/translate/convert/accesskey.py", line 24, in <module>
    from translate.storage.placeables.general import XMLEntityPlaceable
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/__init__.py", line 47, in <module>
    from . import base
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/base.py", line 25, in <module>
    from translate.storage.placeables.interfaces import *
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/interfaces.py", line 25, in <module>
    from translate.storage.placeables.strelem import StringElem
  File "/home/leo/Escritorio/repos/translate/translate/storage/placeables/strelem.py", line 35, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by unho** [comment]
Closing as this no longer happens once I removed interference from system-wide package.
