### ISSUE TITLE
Traceback when running pocount

### ISSUE THREAD

**Issue by unho** [translate/translate#3384]
@claudep I get this:

```pytb
Traceback (most recent call last):
  File "/usr/bin/pocount", line 22, in <module>
    from translate.tools import pocount
  File "/home/leo/Escritorio/repos/translate/translate/tools/pocount.py", line 37, in <module>
    from translate.storage import factory, statsdb
  File "/home/leo/Escritorio/repos/translate/translate/storage/statsdb.py", line 31, in <module>
    from six.moves import _thread, UserDict
ImportError: cannot import name UserDict
```

**Comment by unho** [comment]
I have `six==1.9.0` installed.

**Comment by unho** [comment]
And I ensured that when starting a python console with `python` and then executing `import six` works ok.

**Comment by unho** [comment]
Reopening this since now I completely uninstalled system-wide TTK and restarted everything in a clean slate. The traceback persists:

```pytb
Traceback (most recent call last):
  File "/home/leo/Escritorio/repos/translate/translate/tools/pocount.py", line 37, in <module>
    from translate.storage import factory, statsdb
  File "/home/leo/Escritorio/repos/translate/translate/storage/statsdb.py", line 31, in <module>
    from six.moves import _thread, UserDict
ImportError: cannot import name UserDict
```

**Comment by claudep** [comment]
```
>>> import six
>>> six.__version__
'1.9.0'
>>> from six.moves import UserDict
```
`UserDict` has been introduced in six 1.7.
https://bitbucket.org/gutworth/six/commits/18c5d94f8b3276ce251e50e73b6dead9530ad652

**Comment by unho** [comment]
Now it works. It was some interference from system-wide package.
