### ISSUE TITLE
Traceback when running pofilter

### ISSUE THREAD

**Issue by unho** [translate/translate#3385]
@claudep 

```pytb
Traceback (most recent call last):
  File "/usr/bin/pofilter", line 23, in <module>
    from translate.filters import pofilter
  File "/home/leo/Escritorio/repos/translate/translate/filters/pofilter.py", line 35, in <module>
    from translate.filters import autocorrect, checks
  File "/home/leo/Escritorio/repos/translate/translate/filters/checks.py", line 138, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by unho** [comment]
I have `six==1.9.0` installed.

**Comment by unho** [comment]
And I ensured that when starting a python console with `python` and then executing `import six` works ok.

**Comment by unho** [comment]
Reopening since the issue persists:

```pytb
Traceback (most recent call last):
  File "/home/leo/Escritorio/repos/translate/translate/filters/pofilter.py", line 35, in <module>
    from translate.filters import autocorrect, checks
  File "/home/leo/Escritorio/repos/translate/translate/filters/checks.py", line 138, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by unho** [comment]
It was interference from system-wide package. Closing.
