### ISSUE TITLE
UnicodeEncodeError when running quality check filters

### ISSUE THREAD

**Issue by julen** [translate/translate#3391]
Just switched my local virtualenv from 1.13 to master (1.14rc1), and I can constantly reproduce the following traceback when running quality checks in Pootle (via submissions):
```pytb
Traceback (most recent call last):
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "~/dev/translate/pootle/pootle/apps/pootle_misc/util.py", line 58, in wrapper
    return f(request, *args, **kwargs)
  File "~/dev/translate/pootle/pootle/apps/pootle_store/decorators.py", line 61, in decorated_f
    return f(request, unit, *args, **kwargs)
  File "~/dev/translate/pootle/pootle/apps/pootle_store/views.py", line 594, in submit
    form.save()
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/forms/models.py", line 459, in save
    construct=False)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/forms/models.py", line 105, in save_instance
    instance.save()
  File "~/dev/translate/pootle/pootle/apps/pootle_store/models.py", line 532, in save
    self.update_qualitychecks()
  File "~/dev/translate/pootle/pootle/apps/pootle_store/models.py", line 847, in update_qualitychecks
    qc_failures = checker.run_filters(self, categorised=True)
  File "~/dev/translate/translate/translate/filters/checks.py", line 534, in run_filters
    return super(TranslationChecker, self).run_filters(unit, categorised)
  File "~/dev/translate/translate/translate/filters/checks.py", line 455, in run_filters
    (functionname, unit.source, unit.target, e))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-35: ordinal not in range(128)
```

Switching back to 1.13 makes things work again.

**Comment by julen** [comment]
After further debugging, I can confirm this is **not** a TTK bug. The catch-all `Exception` and the traceback above pointed on the wrong direction. Sorry for the inconveniences!

**Comment by unho** [comment]
@julen No problem, but would be great if you can share where this comes from.

**Comment by unho** [comment]
After discussion with @julen it turns out that this comes from a third party library his Pootle was using.
