### ISSUE TITLE
'apply' is not defined

### ISSUE THREAD

**Issue by unho** [translate/translate#3452]
Originally reported in #3451 by @richmind:

```pytb
NameError("name 'apply' is not defined",)
Traceback (most recent call last):
  File "/Users/user1/anaconda/envs/virt_conda/lib/python3.5/site-packages/translate_toolkit-2.0.0b2-py3.5.egg/translate/misc/wsgiserver/wsgiserver3.py", line 1032, in communicate
    req.respond()
  File "/Users/user1/anaconda/envs/virt_conda/lib/python3.5/site-packages/translate_toolkit-2.0.0b2-py3.5.egg/translate/misc/wsgiserver/wsgiserver3.py", line 828, in respond
    self.server.gateway(self).respond()
  File "/Users/user1/anaconda/envs/virt_conda/lib/python3.5/site-packages/translate_toolkit-2.0.0b2-py3.5.egg/translate/misc/wsgiserver/wsgiserver3.py", line 1839, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/Users/user1/anaconda/envs/virt_conda/lib/python3.5/site-packages/translate_toolkit-2.0.0b2-py3.5.egg/translate/misc/selector.py", line 166, in __call__
    return app(environ, start_response)
  File "/Users/user1/anaconda/envs/virt_conda/lib/python3.5/site-packages/translate_toolkit-2.0.0b2-py3.5.egg/translate/misc/selector.py", line 537, in wsgi_meth
    return apply(meth, args, dict(kwargs))
NameError: name 'apply' is not defined
```

**Comment by unho** [comment]
Thanks a lot. This is actually something that was deprecated on Python 2.3.
