### ISSUE TITLE
Error on writing XLIFF with control characters

### ISSUE THREAD

**Issue by unho** [translate/translate#3561]
This error was reported from Pootle 2.7.6 using Translate Toolkit 1.13.0 when trying to sync to disk a XLIFF file. Related https://github.com/translate/translate/pull/3551 and https://github.com/translate/translate/pull/3555 which fix https://github.com/translate/pootle/issues/5828

```pytb
Traceback (most recent call last):
File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/init.py", line 76, in do_translation_project
self.handle_all_stores(tp, **options)
File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/sync_stores.py", line 48, in handle_all_stores
only_newer=not options['force']
File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/models.py", line 357, in sync
skip_missing=skip_missing, only_newer=only_newer)
File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1998, in sync
changed = unit.sync(match)
File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 673, in sync
unit.target = self.target
File "/var/www/pootle/env/local/lib/python2.7/site-packages/translate/storage/lisa.py", line 163, in settarget
languageNode.text = text
File "src/lxml/lxml.etree.pyx", line 1031, in lxml.etree._Element.text.set (src/lxml/lxml.etree.c:51697)
File "src/lxml/apihelpers.pxi", line 711, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:23071)
File "src/lxml/apihelpers.pxi", line 699, in lxml.etree._createTextNode (src/lxml/lxml.etree.c:22931)
File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8 (src/lxml/lxml.etree.c:30219)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by unho** [comment]
Check if this affects other XML formats, like ts or tmx (add tests).
