### ISSUE TITLE
po2yaml is not able to convert back result of yaml2po

### ISSUE THREAD

**Issue by rootpd** [translate/translate#3826]
Hi,

for the following content I'm not able to convert it to .po and back to .yml.

```yaml
menu:
    api_tokens: Api kľúče
    api_calls: Api volania
    api_logs: Api záznamy
    api_access: Api práva
```

Here is the output file `api.po` generated by calling the `yaml2po api.yml`:

```po
#. extracted from api.yml
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-09-10 23:20+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 2.3.0\n"

#: menu-%3Eapi_tokens
msgid "Api kľúče"
msgstr ""

#: menu-%3Eapi_calls
msgid "Api volania"
msgstr ""

#: menu-%3Eapi_logs
msgid "Api záznamy"
msgstr ""

#: menu-%3Eapi_access
msgid "Api práva"
msgstr ""
```

When I try to convert it back with `po2yaml api.po -t api.po`, I get an error:

```
po2yaml: WARNING: Error processing: input api.po, output None, template api.po: 'mapping values are not allowed here   in "<unicode string>", line 5, column 20:\n    "Project-Id-Version: PACKAGE VERSION\\n"\n 
```

I have `po2yaml 2.3.0` installed, something seems odd. Thanks for checking.

**Comment by rootpd** [comment]
Here is the verbose output:

```
po2yaml: WARNING: Error processing: input api.po, output None, template api.po: Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/translate/storage/yaml.py", line 213, in parse
    self._file = yaml.load(input, OrderedDictYAMLLoader)

  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()

  File "/usr/lib64/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()

  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()

  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()

  File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()

  File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()

  File "/usr/lib64/python3.6/site-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()

  File "/usr/lib64/python3.6/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()

  File "/usr/lib64/python3.6/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())

yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 5, column 20:
    "Project-Id-Version: PACKAGE VERSION\n"
                       ^


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/translate/misc/optrecurse.py", line 536, in recursiveprocess
    fulltemplatepath)

  File "/usr/lib/python3.6/site-packages/translate/convert/convert.py", line 190, in processfile
    fulltemplatepath)

  File "/usr/lib/python3.6/site-packages/translate/misc/optrecurse.py", line 592, in processfile
    **passthroughoptions):

  File "/usr/lib/python3.6/site-packages/translate/convert/po2yaml.py", line 97, in run_converter
    outputthreshold).run()

  File "/usr/lib/python3.6/site-packages/translate/convert/po2yaml.py", line 54, in __init__
    self.template_store = self.TargetStoreClass(template_file)

  File "/usr/lib/python3.6/site-packages/translate/storage/yaml.py", line 136, in __init__
    self.parse(inputfile)

  File "/usr/lib/python3.6/site-packages/translate/storage/yaml.py", line 218, in parse
    raise base.ParseError(message)

translate.storage.base.ParseError: 'mapping values are not allowed here   in "<unicode string>", line 5, column 20:\n    "Project-Id-Version: PACKAGE VERSION\\n"\n                       ^'
```

**Comment by rootpd** [comment]
Very sorry, my bad. The reason for the error was I needed to use original `yml` file as a template, not a `po` file.
