### ISSUE TITLE
Posegment Error:  'xliffunit' object has no attribute 'copy'

### ISSUE THREAD

**Issue by kenton-r** [translate/translate#3962]
I am try to segment a xliff file with posement. The following is the command and the error I get. Is this a bug or something wrong with my setup?

posegment --errorlevel=traceback -i STC_en.xliff -o STC_en_seg.xliff
processing 1 files...
posegment: WARNING: Error processing: input STC_en.xliff, output STC_en_seg.xliff, template None: Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/translate_toolkit-2.5.0-py2.7.egg/translate/misc/optrecurse.py", line 536, in recursiveprocess
    fulltemplatepath)

  File "/usr/local/lib/python2.7/dist-packages/translate_toolkit-2.5.0-py2.7.egg/translate/convert/convert.py", line 190, in processfile
    fulltemplatepath)

  File "/usr/local/lib/python2.7/dist-packages/translate_toolkit-2.5.0-py2.7.egg/translate/misc/optrecurse.py", line 592, in processfile
    **passthroughoptions):

  File "/usr/local/lib/python2.7/dist-packages/translate_toolkit-2.5.0-py2.7.egg/translate/tools/posegment.py", line 86, in segmentfile
    outputstore = convertor.convertstore(inputstore)

  File "/usr/local/lib/python2.7/dist-packages/translate_toolkit-2.5.0-py2.7.egg/translate/tools/posegment.py", line 70, in convertstore
    newunits = self.segmentunit(unit)

  File "/usr/local/lib/python2.7/dist-packages/translate_toolkit-2.5.0-py2.7.egg/translate/tools/posegment.py", line 53, in segmentunit
    newunit = unit.copy()

AttributeError: 'xliffunit' object has no attribute 'copy'

**Comment by unho** [comment]
Can you please share the file you are using so we can easily replicate?
