### ISSUE TITLE
sub2po - Can't find headers file

### ISSUE THREAD

**Issue by RobbyZ** [translate/translate#4155]
On a fresh install of python 3.8 in a new virtualenv, I get the following error:

```
(ttk) C:\dev\translate-toolkit>sub2po -P "C:\dev\translate-toolkit\DA Launch Trailer.ass" "C:\dev\translate-toolkit\trailer.pot"
processing 1 files...
Failed to read file 'C:\Users\Sim\Envs\ttk\lib\site-packages\data\headers\ass': No such file or directory
sub2po: WARNING: Error processing: input C:\dev\translate-toolkit\DA Launch Trailer.ass, output C:\dev\translate-toolkit\trailer.pot, template None: FileNotFoundError(2, 'No such file or directory')
[###########################################] 100%
```

I suspect there is a package required that I have not installed and did not see in the install docs, but maybe it is something else?

I have installed aeidon; here is my package list:

```
(ttk) C:\dev\translate-toolkit>pip list
Package           Version
----------------- ---------
aeidon            1.7.0
ass               0.5.1
certifi           2020.6.20
chardet           3.0.4
idna              2.10
iniparse          0.5
inotify           0.2.10
lxml              4.6.1
nose              1.3.7
pip               20.2.4
requests          2.24.0
setuptools        50.3.2
six               1.15.0
srt               3.4.1
subtitle          2.1
translate-toolkit 3.1.1
urllib3           1.25.11
wheel             0.35.1
```

FYI, [I had the same error](https://github.com/WeblateOrg/weblate/issues/4732) in a linux environment when trying to do this via Weblate.

**Comment by nijel** [comment]
Thanks for investigating this further. Going down it seems to be issue in the aeidon, the actual exception is:

```
Failed to read file '/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/data/headers/ass': No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nijel/weblate/translate/translate/storage/subtitles.py", line 137, in parsefile
    newstore = cls()
  File "/home/nijel/weblate/translate/translate/storage/subtitles.py", line 206, in __init__
    self._subtitlefile = AdvSubStationAlpha(self.filename or '', self.encoding)
  File "/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/aeidon/files/ass.py", line 37, in __init__
    aeidon.files.SubStationAlpha.__init__(self, path, encoding, newline)
  File "/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/aeidon/files/ssa.py", line 43, in __init__
    aeidon.SubtitleFile.__init__(self, path, encoding, newline)
  File "/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/aeidon/file.py", line 53, in __init__
    self.header = (aeidon.util.get_template_header(self.format)
  File "/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/aeidon/util.py", line 269, in get_template_header
    header = read(path, "ascii").rstrip()
  File "/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/aeidon/util.py", line 370, in read
    with open(path, "r", encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nijel/weblate/translate/.venv/lib/python3.8/site-packages/data/headers/ass'
```

It seems the library is looking for files from https://github.com/otsaloma/gaupol/tree/master/data/headers, but these are not part of the aeidon package... Apparently, loading of ass files is not testsuite covered neither in Weblate nor in the translate-toolkit, so this breakage was not noticed.

**Comment by nijel** [comment]
I've added the testcases in https://github.com/translate/translate/pull/4156, though most of them are marked as expected failures now as all subtitle formats with exception of srt (SubRip subtitles file) are broken in current aeidon. The Weblate testsuite does test srt only, so the issue was not caught there either...

**Comment by nijel** [comment]
And created issue on gaupol (where aedion code comes from) to know the status: https://github.com/otsaloma/gaupol/issues/170

**Comment by RobbyZ** [comment]
Thank you, FWIW I confirmed today that dropping in the .ass header file manually from that repo into the data/headers folder allows sub2po to generate the po/pot files.
