### ISSUE TITLE
po2tmx ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

### ISSUE THREAD

**Issue by Jibec** [translate/translate#4183]
Hello,

here is how I use po2tmx: https://pagure.io/fedora-localization-statistics/blob/less_subprocess/f/build_tm.py#_121
here is the faulty file: https://jibecfed.fedorapeople.org/partage/ar.po.gz
here is the stacktrace:

```
Traceback (most recent call last):
  File "/home/jb/Projects/fedora-localization-statistics/./build_tm.py", line 201, in <module>
    main()
  File "/home/jb/Projects/fedora-localization-statistics/./build_tm.py", line 70, in main
    process_tmx(lang_code, compendium_file, tmx_file)
  File "/home/jb/Projects/fedora-localization-statistics/./build_tm.py", line 122, in process_tmx
    tmx_file_result = po2tmx.convertpo(
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/convert/po2tmx.py", line 70, in convertpo
    convertor.convertfiles(inputfile, outputfile.tmxfile, sourcelanguage,
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/convert/po2tmx.py", line 62, in convertfiles
    tmxfile.addtranslation(source, sourcelanguage, translation,
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/tmx.py", line 152, in addtranslation
    unit = self.addsourceunit(source)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/lisa.py", line 297, in addsourceunit
    newunit = self.UnitClass(source)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/lisa.py", line 59, in __init__
    super().__init__(source)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/base.py", line 125, in __init__
    self.source = source
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/lisa.py", line 112, in source
    self.setsource(source, sourcelang='en')
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/lisa.py", line 117, in setsource
    self.source_dom = self.createlanguageNode(sourcelang, text, "source")
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/tmx.py", line 44, in createlanguageNode
    seg.text = text
  File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

thanks for your help!

**Comment by nijel** [comment]
One of the problematic strings:

```
#, c-format
msgid "Client Version:\x0314 %s"
msgstr "ﺈﺻﺩﺍﺭ ﺎﻟﺰﺑﻮﻧ:\x0314 %s"
```
I'm not sure whether using control char `\x03` (^C) is allowed in PO files, but it breaks when trying to write that to XML. There are more control chars present in the PO file which will trigger this.

**Comment by Jibec** [comment]
Le 2020-12-01 09:43, Michal Čihař a écrit :
> One of the problematic strings:
> 
> #, c-format
> msgid "Client Version:\x0314 %s"
> msgstr "ﺈﺻﺩﺍﺭ ﺎﻟﺰﺑﻮﻧ:\x0314 %s"

ok thanks.

do you think the script could raise a warning with the msgid causing 
issue and ignore the unit?
or do you have any other suggestion?

Note: the translate scripts available here are great, I'll use it quite 
a lot in the coming months, it would be great if there were a little bit 
easier to use in python scripts for noobs like me ;)
There is quite a lot of dependencies to command line arguments, which 
are different from one file to another and complex with my level of 
Python to understand.

**Comment by nijel** [comment]
There is a lot of space to improve the translate-toolkit codebase, and there is almost nobody to that work. The convertors refactoring has own issue at https://github.com/translate/translate/issues/3573

**Comment by Jibec** [comment]
I'm unsure I have the required level in Python to do such refactoring.
Or maybe you are willing to do specific mentorship/guidance?
What easy task could I start with?

**Comment by nijel** [comment]
I didn't mean that you should be doing that - it's certainly not an easy task to start with... There is https://github.com/translate/translate/labels/easyhack, but I'm not sure how much up to date that is (given that newest issue on the list is from 2016).
