### ISSUE TITLE
po2tmx: I can't understand the ValueError message

### ISSUE THREAD

**Issue by Jibec** [translate/translate#4276]
hi,

I'm using the tmx converter like this:
```
def process_tmx(lang, source, dest):
    """ Generate a translation memory from a po file """

    outputfile = po2tmx.tmxmultifile(dest)
    po2tmx.convertpo(
        inputfile=BytesIO(open(source, "r").read().encode()),
        outputfile=outputfile,
        templatefile=None,
        sourcelanguage="en",
        targetlanguage=lang,
        comment="source",
    )

    outputfile.tmxfile.savefile(dest)
```

but this file raise an error: https://jibecfed.fedorapeople.org/partage/es.zip

Here is the stacktrace, I don't understand the message, it says on line 18499? Removing this line doesn't change anything.

```
Traceback (most recent call last):
  File "/home/jb/Projects/fedora-localization-statistics/./build_tm.py", line 318, in <module>
    main()
  File "/home/jb/Projects/fedora-localization-statistics/./build_tm.py", line 86, in main
    process_tmx(lang_code, compendium_file, tmx_file)
  File "/home/jb/Projects/fedora-localization-statistics/./build_tm.py", line 237, in process_tmx
    po2tmx.convertpo(
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/convert/po2tmx.py", line 82, in convertpo
    convertor.convertfiles(
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/convert/po2tmx.py", line 49, in convertfiles
    inputstore = po.pofile(inputfile)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/pypo.py", line 844, in __init__
    super().__init__(inputfile, **kwargs)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/pocommon.py", line 204, in __init__
    self.parse(inputfile)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/pypo.py", line 860, in parse
    poparser.parse_units(poparser.ParseState(input, self.create_unit), self)
  File "/home/jb/Projects/fedora-localization-statistics/venv/lib/python3.9/site-packages/translate/storage/poparser.py", line 392, in parse_units
    raise ValueError(f"Syntax error on line {parse_state.lineno}")
ValueError: Syntax error on line 18499
```

Using the command line:  `po2tmx -i es.po -o out.tmx -l es` works fine..
Any advice on how to investigate this?

Thanks for your help

**Comment by nijel** [comment]
I think the problem might be in CR characters on the previous line - it is the middle of the comment and I think it confused the parser, and it treats it as an additional line. There are more occurrences of this in the vinagre comments.

**Comment by Jibec** [comment]
thanks for your answer, sorry but it raises the following questions:
how did you detect it was the CR charaters?
how did you detect it comes from vinagre?
why does it work calling the command line argument and not using direct python code?

**Comment by nijel** [comment]
I looked at the problematic lines with editor which shows these chars in mixed newline files (I'm using vim),

The difference in behavior is caused by newline autodetection which worked differently in both cases, but I really didn't investigate that part.

**Comment by nijel** [comment]
I *think* this should be better since 6408c442599846a349972040d6984c1e42ce08b5, but the original files are no longer available, so I can't verify that.
