### ISSUE TITLE
Fluent-backed units are not syntax-checked and may completely break Weblate

### ISSUE THREAD

**Issue by flaki** [translate/translate#4448]
I've spent the better part of the day debugging a 500 error from Weblate that manifested pretty much out of the blue in random places. As it turns out the root of the issue was a honest mistake from one of the Chinese translators, who translated the string `Note to organizers ({ -optional })` to `给组织者的附注 ({ -可选 })`. Notice the `{ -optional }` bit which is a [term](https://projectfluent.org/fluent/guide/terms.html) in fluent, an internal reference. Should this have happened with a latin language, we might have never noticed, but this caused a syntax error in the parser later on.

The worst issue (that probably belongs to Weblate in the first place) is allowing such invalid syntax to be entered and saved in the first place. The issue was so severe that even discoverability issues aside, the problem could only be fixed by manually editing the PostgreSQL database itself, trying to edit a previously saved invalid sequence like this resulted in 500 error as well. The issue can be reproduced when repo operations are attempted or the "Download translation" button hit. This also means that in the case of linked repositories in other components, the 500 error can even surface in perfectly valid repositories (or, in my case, even in components backed by a different file format, not Fluent).

The reason I'm filing this bug primarily here is because it was `translate/storage` that eventually made this issue harder to debug than it needed to be. This is the error that is reported:

```
File "[..]/site-packages/fluent/syntax/stream.py", line 258, in take_id_start
  raise ParseError('E0004', 'a-zA-Z')

Exception Type: ParseError at /file-sync/content/blogposts/
Exception Value: a-zA-Z
Request information:
USER: Weblate Admin
```

Before the broken ftl file gets handed to `fluent.syntax` there is a serialization step:

```
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/translate/storage/fluent.py", line 197, in serialize
    body = [unit.to_entry() for unit in self.units]
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/translate/storage/fluent.py", line 197, in <listcomp>
    body = [unit.to_entry() for unit in self.units]
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/translate/storage/fluent.py", line 149, in to_entry
    value = fp.maybe_get_pattern(FluentParserStream(self.source))
```

The primary issue debugging the problem is that none of the error message, or the full backtrace, or the extended call chain information shows anything useful to pinpoint *where* did the broken parsing occur. Because the ftl breaks in serialization there's also no temporary file created.

The full backtrace:

<details>

```
Request Method: POST
Request URL: http://weblate.rustfest.global/file-sync/content/blogposts/
Django Version: 3.2.7
Python Executable: /home/weblate/weblate-env/bin/uwsgi
Python Version: 3.8.10
Python Path: ['/', '/home/weblate/weblate-env/lib/python3.8/site-packages/git/ext/gitdb', '.', '', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/weblate/weblate-env/lib/python3.8/site-packages', '/home/weblate/weblate-env/lib/python3.8/site-packages/gitdb/ext/smmap']
Server time: Fri, 08 Oct 2021 11:25:58 +0000
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware',
 'weblate.wladmin.middleware.ManageMiddleware']


Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/views/git.py", line 243, in file_sync_component
    return perform_file_sync(request, obj)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/views/git.py", line 118, in perform_file_sync
    return execute_locked(
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/views/git.py", line 35, in execute_locked
    result = call(*args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/component.py", line 154, in on_link_wrapper
    return getattr(linked, func.__name__)(*args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/component.py", line 155, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/component.py", line 1537, in do_file_sync
    return self.commit_pending("file-sync", request.user if request else None)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/component.py", line 155, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/component.py", line 1570, in commit_pending
    translation.commit_pending(reason, user, skip_push=True, signals=False)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/translation.py", line 559, in commit_pending
    self.update_units(units, store, author_name, author.id)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/models/translation.py", line 733, in update_units
    store.save()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/formats/ttkit.py", line 304, in save
    self.save_atomic(self.storefile, self.save_content)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/formats/base.py", line 314, in save_atomic
    callback(temp)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/formats/ttkit.py", line 300, in save_content
    self.store.serialize(handle)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/translate/storage/fluent.py", line 197, in serialize
    body = [unit.to_entry() for unit in self.units]
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/translate/storage/fluent.py", line 197, in <listcomp>
    body = [unit.to_entry() for unit in self.units]
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/translate/storage/fluent.py", line 149, in to_entry
    value = fp.maybe_get_pattern(FluentParserStream(self.source))
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 346, in maybe_get_pattern
    return self.get_pattern(ps, is_block=False)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 11, in decorated
    return fn(self, ps, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 388, in get_pattern
    element = self.get_placeable(ps)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 11, in decorated
    return fn(self, ps, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 497, in get_placeable
    expression = self.get_expression(ps)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 11, in decorated
    return fn(self, ps, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 503, in get_expression
    selector = self.get_inline_expression(ps)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 11, in decorated
    return fn(self, ps, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 568, in get_inline_expression
    id = self.get_identifier(ps)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 11, in decorated
    return fn(self, ps, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/parser.py", line 236, in get_identifier
    name = ps.take_id_start()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/fluent/syntax/stream.py", line 258, in take_id_start
    raise ParseError('E0004', 'a-zA-Z')
```

</details>

I eventually managed to trace the issue to [`to_entry()` in `translate/storage/fluent.py`](https://github.com/translate/translate/blob/master/translate/storage/fluent.py#L143). I am not a Python developer, but to my understanding if `self`, that is `translate.storage.fluent.FluentUnit` in here came with an appropriate [`__repr__`](https://docs.python.org/3/library/functions.html#repr) than that would have made this issue trivially visible in the error logs sent by Weblate (but probably ensuring that if the internal parser has thrown we augment the error message itself with some of this data could be even more useful):

![image](https://user-images.githubusercontent.com/2089432/136582192-2c40fdfe-8359-4b8a-ae1a-7898e47d0c8e.png)

I decided to post this as, even though at the end of the day this is not a bug per se, fixing this proactively might save some Fluent users a couple hours of debugging and weird breakage, and also so I needn't write a blogpost about it. :stuck_out_tongue: 

Feel free to file a follow-up bug in Weblate for syntax-checking Fluent entries before Save if you believe it would be appropriate.

**Comment by henry-torproject** [comment]
@nijel I can handle this along with https://github.com/translate/translate/issues/4649 which I'm currently working on.

It would be easy to throw on `FluentFile.serialize`, but it might be better if we can also expose this per-translation-unit on weblate. How does weblate expose syntax errors per `TranslationUnit`? I would have assumed it would use `TranslationUnit.geterrors`, but I can't find a call to this in weblate.

**Comment by nijel** [comment]
The proper way of handling this in Weblate would be to add a check for that. The strings are not saved to a file immediately, so we do not have access to the existing FluentFile at that point (it is not possible for performance reasons). The checks are executed upon saving and are supposed to catch this kind of issues.

The `geterrors` does effectively nothing since 89df430c3919f77dd8501be9cd401e47499c2744, it was kept to avoid breaking existing consumers.
