### ISSUE TITLE
Generated wheels contain duplicate files, breaking installer

### ISSUE THREAD

**Issue by mgorny** [translate/translate#4582]
The wheels generated by this package's `setup.py` contain duplicate copies of the Python files, e.g.:

```
$ python setup.py bdist_wheel
[...]
$ unzip -l dist/translate_toolkit-3.6.0-py3-none-any.whl | grep translate/__init__\.py
     1816  02-25-2022 23:20   translate/__init__.py
     1816  02-25-2022 23:20   usr/lib/python3.10/site-packages/translate/__init__.py
```

or:

```
$ python -m build -w
[...]
$ unzip -l dist/translate_toolkit-3.6.0-py3-none-any.whl | grep translate/__init__\.py
     1816  02-25-2022 23:20   translate/__init__.py
     1816  02-25-2022 23:20   translate_toolkit-3.6.0.data/data/lib/python3.10/site-packages/translate/__init__.py
```

My guess is that the .py files get picked up as data files somehow.

This is problematic not only because it fattens up wheels with duplicate files but also breaks installer, effectively making it impossible to switch to PEP517 builds on Gentoo:

```pytb
$ python -m installer --destdir=/tmp/z2 dist/translate_toolkit-3.6.0-py3-none-any.whl 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/installer/__main__.py", line 84, in <module>
    main(sys.argv[1:], "python -m installer")
  File "/usr/lib/python3.10/site-packages/installer/__main__.py", line 80, in main
    installer.install(source, destination, {})
  File "/usr/lib/python3.10/site-packages/installer/_core.py", line 109, in install
    record = destination.write_file(
  File "/usr/lib/python3.10/site-packages/installer/destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
  File "/usr/lib/python3.10/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /tmp/z2/usr/lib/python3.10/site-packages/translate/__init__.py
```
```

**Comment by nijel** [comment]
The `setup.py` needs a massive cleanup. I think that most of its code can be replaced by standard setuptools features...

**Comment by mgorny** [comment]
Quite possible. You may also want to consider using [flit](https://flit.readthedocs.io/en/latest/) as a modern alternative that has saner defaults.

**Comment by nijel** [comment]
I do have some knowledge of setuptools, but none of flit, so that is definitely not something I'd do. I've started with the cleanup in #4587.
